from .product_views import ListCreateProductAPIView
from .product_views import DairyListCreateAPIView
from .product_views import DairyRetrieveUpdateDestroyAPIView

from .users_view import UserListCreateAPIView
from .users_view import ShippingAddressListCreateAPIView
from .users_view import UserRetrieveUpdateDestroyAPIView